A = A_orig; Z = Z_orig; T = T_orig>0; S = S_orig>0;
[MA,NA] = size(A); [MZ,NZ] = size(Z); 
ncovs = size(T,2)-1; % the first column of T,S should be all ones ;
cov_cat_A = T*transpose(2.^(0:ncovs)); cov_cat_Z = S*transpose(2.^(0:ncovs));
cov_A_up_orig_=cell(ncovs,1); 
cov_A_dn_orig_=cell(ncovs,1); 
cov_Z_up_orig_=cell(ncovs,1);
cov_Z_dn_orig_=cell(ncovs,1);
for ncov=0:ncovs-1;
cov_A_up_orig_{1+ncov} = find(T(:,1+1+ncov)==1);
cov_A_dn_orig_{1+ncov} = find(T(:,1+1+ncov)==0);
cov_Z_up_orig_{1+ncov} = find(S(:,1+1+ncov)==1);
cov_Z_dn_orig_{1+ncov} = find(S(:,1+1+ncov)==0);
end;%for ncov=0:ncovs-1;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Zcs_all = zeros(MA+MZ,NA); Zir_all = zeros(MA+MZ,NA); X_P_all = 0.5 + zeros(MA,NA); X_T_all = zeros(NA,1);
for nc=1:NA;
tmp_vec = [A(:,nc) ; Z(:,nc)]; tmp_Aij = zeros(size(tmp_vec)); tmp_Aij(1:MA)=1; tmp_Zij = zeros(size(tmp_vec)); tmp_Zij(MA + (1:MZ))=1;
[tmp_val,tmp_ij] = sort(tmp_vec,'ascend'); [tmp_val,tmp_ir] = sort(tmp_ij,'ascend');
tmp_Aij = tmp_Aij(tmp_ij); tmp_Zij = tmp_Zij(tmp_ij); tmp_Zcs = cumsum(tmp_Zij);
tmp_auc = (mean(find(tmp_Aij))-mean(find(tmp_Zij)))/length(tmp_vec) + 0.5;
% if either block of tmp_vec is empty, we need to fix tmp_auc ;
if ~isfinite(tmp_auc); tmp_auc = 0.5; end;
% test with: tmp_x=0; for nra=1:MA;for nrz=1:MZ; tmp_x=tmp_x+(A(nra,nc)>Z(nrz,nc)); end;end;
% tmp_X = (mean(find(tmp_Aij))-mean(find(tmp_Zij)) + 0.5*(MA+MZ))*(MA*MZ)/(MA+MZ);
% tmp_X = ((sum(find(tmp_Aij))*MZ-sum(find(tmp_Zij)*MA))/(MA+MZ) + 0.5*MA*MZ);
tmp_X = sum(tmp_Zcs(find(tmp_Aij)));
% at this point length(find(Z(:,nc)<A(ij2,nc))) should equal tmp_Zcs(tmp_ir(ij2)) for all ij2;
% test with: for ij2=1:MA;disp(sprintf(' %% %d vs %d',length(find(Z(:,nc)<A(ij2,nc))),tmp_Zcs(tmp_ir(ij2))));end;
Zcs_all(:,nc) = tmp_Zcs;
Zir_all(:,nc) = tmp_ir;
X_T_all(nc) = tmp_X;
% Note that, with this construction, X_T_all = sum(X_P_all,1);
for nl=1:MA; X_P_all(nl,nc) = tmp_Zcs(tmp_ir(nl)); if ~isfinite(X_P_all(nl,nc)); X_P_all(nl,nc) = 0; end; end;
%if test_flag; tmp_norm = 0; for nl=1:MA; tmp_norm = tmp_norm + (length(find(Z(:,nc)<A(nl,nc))) - tmp_Zcs(tmp_ir(nl))).^2; end; disp(sprintf(' %% cs-vs-ir error: %f',tmp_norm)); end;%if test_flag;
end;%for nc=1:NA;
if test_flag; tmp_norm = 0; for nc=1:NA; for nl=1:MA; tmp_norm = tmp_norm + (length(find(Z(:,nc)<A(nl,nc))) - X_P_all(nl,nc)).^2; end; end; disp(sprintf(' %% _all cs-vs-ir error: %f',tmp_norm)); end;%if test_flag;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
Zcs_xx_up = cell(ncovs,1); Zir_xx_up = cell(ncovs,1); X_T_xx_up = zeros(NA,ncovs); X_P_xx_up = cell(ncovs,1);
Zcs_xx_dn = cell(ncovs,1); Zir_xx_dn = cell(ncovs,1); X_T_xx_dn = zeros(NA,ncovs); X_P_xx_dn = cell(ncovs,1);
Zcs_up_up = cell(ncovs,1); Zir_up_up = cell(ncovs,1); X_T_up_up = zeros(NA,ncovs); X_P_up_up = cell(ncovs,1);
Zcs_up_dn = cell(ncovs,1); Zir_up_dn = cell(ncovs,1); X_T_up_dn = zeros(NA,ncovs); X_P_up_dn = cell(ncovs,1);
Zcs_dn_up = cell(ncovs,1); Zir_dn_up = cell(ncovs,1); X_T_dn_up = zeros(NA,ncovs); X_P_dn_up = cell(ncovs,1);
Zcs_dn_dn = cell(ncovs,1); Zir_dn_dn = cell(ncovs,1); X_T_dn_dn = zeros(NA,ncovs); X_P_dn_dn = cell(ncovs,1);
for ncov=1:ncovs;
Zcs_xx_up{ncov} = zeros(MA + length(cov_Z_up_orig_{ncov}),NA); Zir_xx_up{ncov} = zeros(MA + length(cov_Z_up_orig_{ncov}),NA); X_P_xx_up{ncov} = zeros(MA,NA); 
Zcs_xx_dn{ncov} = zeros(MA + length(cov_Z_dn_orig_{ncov}),NA); Zir_xx_dn{ncov} = zeros(MA + length(cov_Z_dn_orig_{ncov}),NA); X_P_xx_dn{ncov} = zeros(MA,NA); 
Zcs_up_up{ncov} = zeros(length(cov_A_up_orig_{ncov}) + length(cov_Z_up_orig_{ncov}),NA); Zir_up_up{ncov} = zeros(length(cov_A_up_orig_{ncov}) + length(cov_Z_up_orig_{ncov}),NA); X_P_up_up{ncov} = zeros(length(cov_A_up_orig_{ncov}),NA); 
Zcs_up_dn{ncov} = zeros(length(cov_A_up_orig_{ncov}) + length(cov_Z_dn_orig_{ncov}),NA); Zir_up_dn{ncov} = zeros(length(cov_A_up_orig_{ncov}) + length(cov_Z_dn_orig_{ncov}),NA); X_P_up_dn{ncov} = zeros(length(cov_A_up_orig_{ncov}),NA); 
Zcs_dn_up{ncov} = zeros(length(cov_A_dn_orig_{ncov}) + length(cov_Z_up_orig_{ncov}),NA); Zir_dn_up{ncov} = zeros(length(cov_A_dn_orig_{ncov}) + length(cov_Z_up_orig_{ncov}),NA); X_P_dn_up{ncov} = zeros(length(cov_A_dn_orig_{ncov}),NA); 
Zcs_dn_dn{ncov} = zeros(length(cov_A_dn_orig_{ncov}) + length(cov_Z_dn_orig_{ncov}),NA); Zir_dn_dn{ncov} = zeros(length(cov_A_dn_orig_{ncov}) + length(cov_Z_dn_orig_{ncov}),NA); X_P_dn_dn{ncov} = zeros(length(cov_A_dn_orig_{ncov}),NA); 
for nc=1:NA;
tmp_vec = [A(1:MA,nc) ; Z(cov_Z_up_orig_{ncov},nc)]; tmp_Aij = zeros(size(tmp_vec)); tmp_Aij(1:MA)=1; tmp_Zij = zeros(size(tmp_vec)); tmp_Zij(MA + (1:length(cov_Z_up_orig_{ncov})))=1;
[tmp_val,tmp_ij] = sort(tmp_vec,'ascend'); [tmp_val,tmp_ir] = sort(tmp_ij,'ascend');
tmp_Aij = tmp_Aij(tmp_ij); tmp_Zij = tmp_Zij(tmp_ij); tmp_Zcs = cumsum(tmp_Zij);
tmp_auc = (mean(find(tmp_Aij))-mean(find(tmp_Zij)))/length(tmp_vec) + 0.5; if ~isfinite(tmp_auc); tmp_auc = 0.5; end;
tmp_X = sum(tmp_Zcs(find(tmp_Aij)));
Zcs_xx_up{ncov}(:,nc) = tmp_Zcs; Zir_xx_up{ncov}(:,nc) = tmp_ir; X_T_xx_up(nc,ncov) = tmp_X;
for nl=1:MA; X_P_xx_up{ncov}(nl,nc) = tmp_Zcs(tmp_ir(nl)); if ~isfinite(X_P_xx_up{ncov}(nl,nc)); X_P_xx_up{ncov}(nl,nc) = 0; end; end;
%if test_flag; tmp_norm = 0; for nl=1:MA; tmp_norm = tmp_norm + (length(find(Z(cov_Z_up_orig_{ncov},nc)<A(nl,nc))) - tmp_Zcs(tmp_ir(nl))).^2; end; disp(sprintf(' %% cs-vs-ir error: %f',tmp_norm)); end;%if test_flag;
tmp_vec = [A(1:MA,nc) ; Z(cov_Z_dn_orig_{ncov},nc)]; tmp_Aij = zeros(size(tmp_vec)); tmp_Aij(1:MA)=1; tmp_Zij = zeros(size(tmp_vec)); tmp_Zij(MA + (1:length(cov_Z_dn_orig_{ncov})))=1;
[tmp_val,tmp_ij] = sort(tmp_vec,'ascend'); [tmp_val,tmp_ir] = sort(tmp_ij,'ascend');
tmp_Aij = tmp_Aij(tmp_ij); tmp_Zij = tmp_Zij(tmp_ij); tmp_Zcs = cumsum(tmp_Zij);
tmp_auc = (mean(find(tmp_Aij))-mean(find(tmp_Zij)))/length(tmp_vec) + 0.5; if ~isfinite(tmp_auc); tmp_auc = 0.5; end;
tmp_X = ((sum(find(tmp_Aij))*length(cov_Z_dn_orig_{ncov})-sum(find(tmp_Zij)*MA))/(MA+length(cov_Z_dn_orig_{ncov})) + 0.5*MA*length(cov_Z_dn_orig_{ncov}));
Zcs_xx_dn{ncov}(:,nc) = tmp_Zcs; Zir_xx_dn{ncov}(:,nc) = tmp_ir; X_T_xx_dn(nc,ncov) = tmp_X;
for nl=1:MA; X_P_xx_dn{ncov}(nl,nc) = tmp_Zcs(tmp_ir(nl)); if ~isfinite(X_P_xx_dn{ncov}(nl,nc)); X_P_xx_dn{ncov}(nl,nc) = 0; end; end;
%if test_flag; tmp_norm = 0; for nl=1:MA; tmp_norm = tmp_norm + (length(find(Z(cov_Z_dn_orig_{ncov},nc)<A(nl,nc))) - tmp_Zcs(tmp_ir(nl))).^2; end; disp(sprintf(' %% cs-vs-ir error: %f',tmp_norm)); end;%if test_flag;
tmp_vec = [A(cov_A_up_orig_{ncov},nc) ; Z(cov_Z_up_orig_{ncov},nc)]; 
tmp_Aij = zeros(size(tmp_vec)); tmp_Aij(1:length(cov_A_up_orig_{ncov}))=1; tmp_Zij = zeros(size(tmp_vec)); tmp_Zij(length(cov_A_up_orig_{ncov}) + (1:length(cov_Z_up_orig_{ncov})))=1;
[tmp_val,tmp_ij] = sort(tmp_vec,'ascend'); [tmp_val,tmp_ir] = sort(tmp_ij,'ascend');
tmp_Aij = tmp_Aij(tmp_ij); tmp_Zij = tmp_Zij(tmp_ij); tmp_Zcs = cumsum(tmp_Zij);
tmp_auc = (mean(find(tmp_Aij))-mean(find(tmp_Zij)))/length(tmp_vec) + 0.5; if ~isfinite(tmp_auc); tmp_auc = 0.5; end;
tmp_X = sum(tmp_Zcs(find(tmp_Aij)));
Zcs_up_up{ncov}(:,nc) = tmp_Zcs; Zir_up_up{ncov}(:,nc) = tmp_ir; X_T_up_up(nc,ncov) = tmp_X;
for nl=1:length(cov_A_up_orig_{ncov}); X_P_up_up{ncov}(nl,nc) = tmp_Zcs(tmp_ir(nl)); if ~isfinite(X_P_up_up{ncov}(nl,nc)); X_P_up_up{ncov}(nl,nc) = 0; end; end;
%if test_flag; tmp_norm = 0; for nl=1:length(cov_A_up_orig_{ncov}); tmp_norm = tmp_norm + (length(find(Z(cov_Z_up_orig_{ncov},nc)<A(cov_A_up_orig_{ncov}(nl),nc))) - tmp_Zcs(tmp_ir(nl))).^2; end; disp(sprintf(' %% cs-vs-ir error: %f',tmp_norm)); end;%if test_flag;
tmp_vec = [A(cov_A_up_orig_{ncov},nc) ; Z(cov_Z_dn_orig_{ncov},nc)]; 
tmp_Aij = zeros(size(tmp_vec)); tmp_Aij(1:length(cov_A_up_orig_{ncov}))=1; tmp_Zij = zeros(size(tmp_vec)); tmp_Zij(length(cov_A_up_orig_{ncov}) + (1:length(cov_Z_dn_orig_{ncov})))=1;
[tmp_val,tmp_ij] = sort(tmp_vec,'ascend'); [tmp_val,tmp_ir] = sort(tmp_ij,'ascend');
tmp_Aij = tmp_Aij(tmp_ij); tmp_Zij = tmp_Zij(tmp_ij); tmp_Zcs = cumsum(tmp_Zij);
tmp_auc = (mean(find(tmp_Aij))-mean(find(tmp_Zij)))/length(tmp_vec) + 0.5; if ~isfinite(tmp_auc); tmp_auc = 0.5; end;
tmp_X = sum(tmp_Zcs(find(tmp_Aij)));
Zcs_up_dn{ncov}(:,nc) = tmp_Zcs; Zir_up_dn{ncov}(:,nc) = tmp_ir; X_T_up_dn(nc,ncov) = tmp_X;
for nl=1:length(cov_A_up_orig_{ncov}); X_P_up_dn{ncov}(nl,nc) = tmp_Zcs(tmp_ir(nl)); if ~isfinite(X_P_up_dn{ncov}(nl,nc)); X_P_up_dn{ncov}(nl,nc) = 0; end; end;
%if test_flag; tmp_norm = 0; for nl=1:length(cov_A_up_orig_{ncov}); tmp_norm = tmp_norm + (length(find(Z(cov_Z_dn_orig_{ncov},nc)<A(cov_A_up_orig_{ncov}(nl),nc))) - tmp_Zcs(tmp_ir(nl))).^2; end; disp(sprintf(' %% cs-vs-ir error: %f',tmp_norm)); end;%if test_flag;
tmp_vec = [A(cov_A_dn_orig_{ncov},nc) ; Z(cov_Z_up_orig_{ncov},nc)]; 
tmp_Aij = zeros(size(tmp_vec)); tmp_Aij(1:length(cov_A_dn_orig_{ncov}))=1; tmp_Zij = zeros(size(tmp_vec)); tmp_Zij(length(cov_A_dn_orig_{ncov}) + (1:length(cov_Z_up_orig_{ncov})))=1;
[tmp_val,tmp_ij] = sort(tmp_vec,'ascend'); [tmp_val,tmp_ir] = sort(tmp_ij,'ascend');
tmp_Aij = tmp_Aij(tmp_ij); tmp_Zij = tmp_Zij(tmp_ij); tmp_Zcs = cumsum(tmp_Zij);
tmp_auc = (mean(find(tmp_Aij))-mean(find(tmp_Zij)))/length(tmp_vec) + 0.5; if ~isfinite(tmp_auc); tmp_auc = 0.5; end;
tmp_X = sum(tmp_Zcs(find(tmp_Aij)));
Zcs_dn_up{ncov}(:,nc) = tmp_Zcs; Zir_dn_up{ncov}(:,nc) = tmp_ir; X_T_dn_up(nc,ncov) = tmp_X;
for nl=1:length(cov_A_dn_orig_{ncov}); X_P_dn_up{ncov}(nl,nc) = tmp_Zcs(tmp_ir(nl)); if ~isfinite(X_P_dn_up{ncov}(nl,nc)); X_P_dn_up{ncov}(nl,nc) = 0; end; end;
%if test_flag; tmp_norm = 0; for nl=1:length(cov_A_dn_orig_{ncov}); tmp_norm = tmp_norm + (length(find(Z(cov_Z_up_orig_{ncov},nc)<A(cov_A_dn_orig_{ncov}(nl),nc))) - tmp_Zcs(tmp_ir(nl))).^2; end; disp(sprintf(' %% cs-vs-ir error: %f',tmp_norm)); end;%if test_flag;
tmp_vec = [A(cov_A_dn_orig_{ncov},nc) ; Z(cov_Z_dn_orig_{ncov},nc)]; 
tmp_Aij = zeros(size(tmp_vec)); tmp_Aij(1:length(cov_A_dn_orig_{ncov}))=1; tmp_Zij = zeros(size(tmp_vec)); tmp_Zij(length(cov_A_dn_orig_{ncov}) + (1:length(cov_Z_dn_orig_{ncov})))=1;
[tmp_val,tmp_ij] = sort(tmp_vec,'ascend'); [tmp_val,tmp_ir] = sort(tmp_ij,'ascend');
tmp_Aij = tmp_Aij(tmp_ij); tmp_Zij = tmp_Zij(tmp_ij); tmp_Zcs = cumsum(tmp_Zij);
tmp_auc = (mean(find(tmp_Aij))-mean(find(tmp_Zij)))/length(tmp_vec) + 0.5; if ~isfinite(tmp_auc); tmp_auc = 0.5; end;
tmp_X = sum(tmp_Zcs(find(tmp_Aij)));
Zcs_dn_dn{ncov}(:,nc) = tmp_Zcs; Zir_dn_dn{ncov}(:,nc) = tmp_ir; X_T_dn_dn(nc,ncov) = tmp_X;
for nl=1:length(cov_A_dn_orig_{ncov}); X_P_dn_dn{ncov}(nl,nc) = tmp_Zcs(tmp_ir(nl)); if ~isfinite(X_P_dn_dn{ncov}(nl,nc)); X_P_dn_dn{ncov}(nl,nc) = 0; end; end;
%if test_flag; tmp_norm = 0; for nl=1:length(cov_A_dn_orig_{ncov}); tmp_norm = tmp_norm + (length(find(Z(cov_Z_dn_orig_{ncov},nc)<A(cov_A_dn_orig_{ncov}(nl),nc))) - tmp_Zcs(tmp_ir(nl))).^2; end; disp(sprintf(' %% cs-vs-ir error: %f',tmp_norm)); end;%if test_flag;
end;%for nc=1:NA;
end;%for ncov=1:ncovs;
if test_flag; tmp_norm = 0; 
for ncov=1:ncovs; for nc=1:NA; for nl=1:MA; tmp_norm = tmp_norm + (length(find(Z(cov_Z_up_orig_{ncov},nc)<A(nl,nc))) - Zcs_xx_up{ncov}(Zir_xx_up{ncov}(nl,nc),nc)).^2; end;end;end;%for ncov=1:ncovs; for nc=1:NA; for nl=1:MA; 
for ncov=1:ncovs; for nc=1:NA; for nl=1:MA; tmp_norm = tmp_norm + (length(find(Z(cov_Z_dn_orig_{ncov},nc)<A(nl,nc))) - Zcs_xx_dn{ncov}(Zir_xx_dn{ncov}(nl,nc),nc)).^2; end;end;end;%for ncov=1:ncovs; for nc=1:NA; for nl=1:MA; 
for ncov=1:ncovs; for nc=1:NA; for nl=1:length(cov_A_up_orig_{ncov}); tmp_norm = tmp_norm + (length(find(Z(cov_Z_up_orig_{ncov},nc)<A(cov_A_up_orig_{ncov}(nl),nc))) - Zcs_up_up{ncov}(Zir_up_up{ncov}(nl,nc),nc)).^2; end;end;end;%for ncov=1:ncovs; for nc=1:NA; for nl=1:length(cov_A_up_orig_{ncov}); 
for ncov=1:ncovs; for nc=1:NA; for nl=1:length(cov_A_up_orig_{ncov}); tmp_norm = tmp_norm + (length(find(Z(cov_Z_dn_orig_{ncov},nc)<A(cov_A_up_orig_{ncov}(nl),nc))) - Zcs_up_dn{ncov}(Zir_up_dn{ncov}(nl,nc),nc)).^2; end;end;end;%for ncov=1:ncovs; for nc=1:NA; for nl=1:length(cov_A_up_orig_{ncov}); 
for ncov=1:ncovs; for nc=1:NA; for nl=1:length(cov_A_dn_orig_{ncov}); tmp_norm = tmp_norm + (length(find(Z(cov_Z_up_orig_{ncov},nc)<A(cov_A_dn_orig_{ncov}(nl),nc))) - Zcs_dn_up{ncov}(Zir_dn_up{ncov}(nl,nc),nc)).^2; end;end;end;%for ncov=1:ncovs; for nc=1:NA; for nl=1:length(cov_A_dn_orig_{ncov}); 
for ncov=1:ncovs; for nc=1:NA; for nl=1:length(cov_A_dn_orig_{ncov}); tmp_norm = tmp_norm + (length(find(Z(cov_Z_dn_orig_{ncov},nc)<A(cov_A_dn_orig_{ncov}(nl),nc))) - Zcs_dn_dn{ncov}(Zir_dn_dn{ncov}(nl,nc),nc)).^2; end;end;end;%for ncov=1:ncovs; for nc=1:NA; for nl=1:length(cov_A_dn_orig_{ncov}); 
disp(sprintf(' %% ncov cs-vs-ir error: %f',tmp_norm));
end;%if test_flag;
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
clear Zcs_xx_up; clear  Zir_xx_up;
clear Zcs_xx_dn; clear  Zir_xx_dn;
clear Zcs_up_up; clear  Zir_up_up;
clear Zcs_up_dn; clear  Zir_up_dn;
clear Zcs_dn_up; clear  Zir_dn_up;
clear Zcs_dn_dn; clear  Zir_dn_dn;
cov_A_up_=cov_A_up_orig_;
cov_A_dn_=cov_A_dn_orig_;
cov_Z_up_=cov_Z_up_orig_;
cov_Z_dn_=cov_Z_dn_orig_;
nrows_rem = MA;
ncols_rem = NA;
X_P_all_orig = X_P_all;X_P_xx_up_orig = X_P_xx_up;X_P_xx_dn_orig = X_P_xx_dn;X_P_up_up_orig = X_P_up_up;X_P_up_dn_orig = X_P_up_dn;X_P_dn_up_orig = X_P_dn_up;X_P_dn_dn_orig = X_P_dn_dn;X_T_all_orig = X_T_all;X_T_xx_up_orig = X_T_xx_up;X_T_xx_dn_orig = X_T_xx_dn;X_T_up_up_orig = X_T_up_up;X_T_up_dn_orig = X_T_up_dn;X_T_dn_up_orig = X_T_dn_up;X_T_dn_dn_orig = X_T_dn_dn;

